version: '3'

networks:
  lw-network:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: database_velez
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gabriel
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=audiency
    volumes:
      - pgdata:/data/postgres
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: gabriel
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  pgdata:
    driver: local
